config/routes.rb
Strict::Application.routes.draw do
  root :to => "home#index"
  devise_for :users
  get "home/index"
  get "/student/dashboard", to: 'student#dashboard'
  resources :user
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
   attr_accessor :login,:name
         validates :username,
  :uniqueness => {
    :case_sensitive => false
  }
  
 
  
  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :name) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me,:name) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :name) }
  end

  def after_sign_in_path_for(resource_or_scope)
  		student_dashboard_path
  end
  def after_sign_out_path_for(resource_or_scope)
		root_path
  end
   def after_inactive_sign_up_path_for(resource_or_scope)
    	student_dashboard_path
  end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def signin
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user

	def authenticate_user
		if user_signed_in?
			redirect_to student_dashboard_path
		end
	end
  def index
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
before_action :authenticate_user!

def dashboard
	render :layout => 'student'
end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/home/_landing.html.erb
		<%= javascript_include_tag "general" %>

<section id="1" class="window section1">
			<section class="landing" id="l0">	
				<div class="container">
					<div class="row">
						<a href="#l1">
							<div class="col-xs-12 col-sm-10 col-sm-push-1 col-md-8 col-md-push-2 title">
								<h1 class="text-center">Strictly Scholarship</h1>
							</div>
						</a>
					</div>
				</div>
				<div id="carousel-example-generic" class="carousel slide slider" data-ride="carousel" data-interval="2000">
  					<!-- Wrapper for slides -->
  					<div class="carousel-inner text-center slider-inner">
    					<div class="item active">
     						<h1>BEST <span class="highlight">SCHOLARSHIPS</span></h1>
     						<br><br>
     					</div>
     					<div class="item">
     						<h1>SHAPING YOUR <span class="highlight">FUTURE</span></h1>
     						<br><br>
     					</div>
	     				<div class="item">
    	 					<h1>LIVE YOUR <span class="highlight">DREAMS</span></h1>
     						<br><br>
    					</div>
  					</div>
  					<!-- Indicators -->
  					<ol class="carousel-indicators indicator">
	    				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
    					<li data-target="#carousel-example-generic" data-slide-to="2"></li>
  					</ol>
				</div>
			</section>
			<section class="landing" id="l1">
				<div class="scroller_anchor"></div>
				<nav class="navbar navbar-inverse navigation scroller" role="navigation">
  					<div class="container-fluid">
	    				<!-- Brand and toggle get grouped for better mobile display -->
    					<div class="navbar-header">
      						<a class="navbar-brand" href="#l0">
      							<div>
      						<%=image_tag("logo.png", :border=>0, :class => "logoimg")%> </div><div><span class="brand">STRICTLY SCHOLARSHIP</span></div></a>
      						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        					<span class="sr-only">Toggle navigation</span>
        						<span class="icon-bar"></span>
        						<span class="icon-bar"></span>
        						<span class="icon-bar"></span>
      						</button>
    					</div>
    					<!-- Collect the nav links, forms, and other content for toggling -->
    					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      						<ul class="nav navbar-nav navbar-right">
	    	   	 				<li><a href="#l1" class="navig active" id="mi1">Scholarships</a></li>
        						<li><a href="#l2" class="navig" id="mi2">Universities</a></li>
        						<li><a href="#l3" class="navig" id="mi3">About</a></li>
        						<li><a href="#l4" class="navig" id="mi4">Blog</a></li>
        						<li><a href="#l5" class="navig" id="mi5" data-toggle="modal" data-target="#signInModal">Join</a></li>
      						</ul>
    					</div><!-- /.navbar-collapse -->
  					</div><!-- /.container-fluid -->
				</nav>
			</section>
			<section class="landing" id="l2">
			
			
			</section>
			<section class="landing" id="l3">
				
			</section>
		</section>
		<section id="2" class="window section2">
			
		</section>
		<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel" aria-hidden="true">
					
		<%= render :partial => "student/login_form"%>
		
		</div>
		
		<%= render :partial => "student/registration_form"%>
		
		<%= render :partial => "student/forgot_password"%>
	
		</div>
		<div class="top">
           <a href="#l0"> ^ </a>
        </div>

app/views/home/index.html.erb
<%= render :partial => "home/landing"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Bootstrap 3</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, maximum-scale=1.0">
		<%= javascript_include_tag "application" %>
		<%= stylesheet_link_tag "application", media: "all" %>
  		<%= csrf_meta_tags %>
    	<!--[if lt IE 9]>
    		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    	<![endif]-->
	</head>
	<body>
	
		<%= yield %>
	</body>
</html>

app/views/student/_forgot_password.html.erb
<%= form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :post }) do |f| %>

<div class="modal fade" id="forgotModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel" aria-hidden="true">
			<div class="modal-dialog loginModal">
				<div class="modal-content loginContent">
					<div class="modal-header">
							<h1 class="modal-title loginHeader">Forgot your Pasword?</h1>
					</div>
					<div class="modal-body loginBody">
						<div class="container-fluid loginContainer">
							<div class="row">
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-envelope"></span>
									
									<%= f.text_field :login, :autofocus => true, :class =>"form-control tbox", :placeholder => "Email", :required => "required" %>
								</div>
								<br>
								<%= button_tag "<h4>Recover Password</h4>".html_safe, :class =>"btn btn-block buttonSignIn", :type => "submit" %>
											
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<% end %>

app/views/student/_login_form.html.erb
<div class="modal-dialog loginModal">
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

  
				<div class="modal-content loginContent">
					<div class="modal-header">
						<h1 class="modal-title loginHeader">
							<span class="glyphicon glyphicon-lock"></span>Sign-In
						</h1>
					</div>
					<div class="modal-body loginBody">
						<div class="container-fluid loginContainer">
						<% if !flash.nil? %>
        					<% flash.each do |name, msg| %>
            				<% if msg.is_a?(String) %>
                			<div class="alert  alert-<%= name == :notice ? "success" : "error" %> alert-block">
                  				<button type="button" class="close" data-dismiss="alert">×</button>
                  				<%= content_tag :div, msg, :id => "flash_#{name}" %>
                			</div>
            			<% end %>
        			<% end %>
    				<% end %>
							<div class="row">
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-user"></span>
									<%= f.text_field :login, :autofocus => true, :class => "form-control tbox", :placeholder => "Email", :required => "required" %></div>
								
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-asterisk"></span>
									
  								<%= f.password_field :password, :class => "form-control tbox", :placeholder => "password", :required => "required" %>
								</div>  
								<br>
								<br>
								<div class="row">
									<div class="col-xs-12 col-sm-6">
										
										<%= button_tag "<h4> Sign In </h4>".html_safe, :class =>"btn btn-block buttonSignIn", :type => "submit" %>
											
										
									</div>
									<div class="col-xs-12 col-sm-6">
										<button type="button" class="btn btn-block buttonForgotPassword" data-dismiss="modal" data-toggle="modal" data-target="#forgotModal">
											<h4>FORGOT PASSWORD</h4>
										</button>
									</div>
								</div>
								<br>
								<div class="register">
									<h3>New to Strictly Scholarship?</h3>
									<button type="button" class="btn btn-block buttonForgotPassword" data-dismiss="modal" data-toggle="modal" data-target="#registerModal">
										<h4>REGISTER</h4>
									</button>
								</div>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<h5 class="pull-left"style="color:white">OR SIGN IN WITH</h5>
						<a href="" class="btn btn-social-icon btn-facebook">
							<i class="fa fa-facebook"></i>
						</a>
						<a class="btn btn-social-icon btn-google-plus">
							<i class="fa fa-google-plus"></i>
						</a>
					</div>
				</div>
			</div>
			<% end %>

app/views/student/_registration_form.html.erb
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>

<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel" aria-hidden="true">
			<div class="modal-dialog loginModal">
				<div class="modal-content loginContent">
					<div class="modal-header">
						<h1 class="modal-title loginHeader">
							<span class="glyphicon glyphicon-pencil" ></span>Register
						</h1>
					</div>
					<div class="modal-body loginBody">
						<div class="container-fluid loginContainer">
							<div class="row">
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-user"></span>
									
									<%= f.text_field :name,:class => "form-control tbox", :placeholder => "Name", :required => "required", :autofocus => true   %>
								</div>
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-user"></span>
									
									<%= f.text_field :username, :class => "form-control tbox", :placeholder=>"Username", :required => "required" %>
								</div>
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-envelope"></span>
									
									<%= f.email_field :email, :class => "form-control tbox", :placeholder => "Email", :required=> "required"%>
								</div>
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-asterisk"></span>
									
									<%= f.password_field :password,:class => "form-control tbox", :placeholder => "Password", :required => "required"%>
								</div>
								<div class="input-group input-group-lg inputBox">
									<span class="input-group-addon glyphicon glyphicon-asterisk"></span>
									
									<%= f.password_field :password_confirmation,:class => "form-control tbox", :placeholder => "Confirm Password", :required => "required"%>
								</div>  
								<br>
								<%= button_tag "<h4> Register </h4>".html_safe, :class =>"btn btn-block buttonSignIn", :type => "submit" %>
								
								<div class="register">
									<h3>Already have an account?</h3>
									<button type="button" class="btn btn-block buttonForgotPassword" data-dismiss="modal" data-toggle="modal" data-target="#signInModal">
										<h4>Sign In</h4>
									</button>
								</div>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<h5 class="pull-left"style="color:white">OR SIGN UP WITH</h5>
						<a href="" class="btn btn-social-icon btn-facebook">
							<i class="fa fa-facebook"></i>
						</a>
						<a class="btn btn-social-icon btn-google-plus">
							<i class="fa fa-google-plus"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
		<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>